sudo: required

services:
  - docker

before_install:
  - docker build -t darivo/vida-operations-service .

script:
  - docker run darivo/vida-operations-service npm test

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push darivo/vida-operations-service
